#!/bin/sh

sudo apt-get -y install trayer volti suckless-tools
sudo apt-get -y install scrot conky gsimplecal
sudo apt-get -y install xfce4-terminal

cd ~
ln -sf .xmonad/xmobarrc .xmobarrc
ln -sf .xmonad/xsessionrc .xsessionrc
ln -sf .xmonad/conkyrc .conkyrc

sudo cp .xmonad/xmonad-session.desktop /usr/share/xsessions/
sudo cp .xmonad/xmonad-plain.session /usr/share/gnome-session/sessions/
sudo cp .xmonad/xmonad-plain.desktop /usr/share/applications/
sudo cp .xmonad/xmonad-session /usr/bin/
