#!/bin/bash
# vim:ft=sh
 
# Load resources
#xrdb -merge .Xresources

# Load keymap
xmodmap ~/.Xmodmap

# Set the background color<
xsetroot -solid '#888888'

# start the composition manager (shadows, transparency, etc.)
# xcompmgr -c &

# Set up an icon tray (should try stalonetray)
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x000000 --height 20 \
 --distancefrom right --distance 450 &

# settings daemon for DBus
gnome-settings-daemon --replace &
sleep 1

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager &
fi

dropbox start -i
davmail &
volti &
/opt/bin/spotify-notify.py -n -s &

/usr/lib/gnome-settings-daemon/gsd-printer &
gnome-screensaver &

# Start Zeitgeist indexing service
zeitgeist-daemon &

# Start gnome-do application launcher
#gnome-do &

conky &

export SSH_ASKPASS="/usr/bin/ssh-askpass"

#exec xmonad
