#!/bin/bash
# vim:ft=sh
 
# Load resources
#xrdb -merge .Xresources

# Load keymap
xmodmap ~/.Xmodmap

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x000000 --height 20 &

# Set the background color<

xsetroot -solid '#888888'

# Fire up apps

#xscreensaver -no-splash &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager &
fi

dropbox start -i
davmail &
volti &

#exec xmonad
